# .github/workflows/ci.yml
name: CI (install & import)

on:
  push:
  pull_request:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install (CPU-safe)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          # requirements.txt 있으면 설치, 없으면 건너뜀
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # CPU 전용 PyTorch
          pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision torchaudio
          # GUI 없는 OpenCV로 고정 (기존 패키지 없으면 무시)
          pip uninstall -y opencv-python || true
          pip install opencv-python-headless
          # 시스템 라이브러리
          sudo apt-get update
          sudo apt-get install -y ffmpeg libgl1

      - name: Import smoke test
        run: |
          python - << 'PY'
import sys
print("Python:", sys.version)
import cv2, torch
print("cv2", cv2.__version__, "torch", torch.__version__)
PY
